from django.urls import path
from . import views
from . import HozmaApi_views
from . import api_views
from rest_framework import permissions
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

app_name = 'wholesale_app'

urlpatterns = [
    # Down here is for car parts
    path('preorder/create/', HozmaApi_views.create_pre_order, name='create_pre_order'),
    path('preorder/last-invoice/', HozmaApi_views.get_sellinvoice_no, name='get_sellinvoice_no'),
    path('preorder/add-item/', HozmaApi_views.Sell_invoice_create_item, name='sell_invoice_create_item'),
    path('hozmabrands/', views.CarParts_page, name='CarParts_page'),
    path('products/', views.item_filter_page, name='item_filter_page'),
    path('hozmaHome/', views.CarPartsHome_page, name='CarPartsHome_page'),
    path('hozmaDashbord/', views.Dashbord_page, name='dashbord'),
    path('brand/<str:brand>/', api_views.brand_items, name='brand_items'),
    path('hozmaCart/', views.Cart_page, name='Cart'),
    path('hozmatrack-order/', views.track_order, name='track_order'),
    path('hozmareturn-policy/', views.return_policy, name='return_policy'),
    path('hozmafaq/', views.faq, name='faq'),
    path('invoice/<str:invoice_no>/', views.invoice, name='invoice_view'),
    path('hozmalogin/', views.hozmalogin, name='hozmalogin'),
    path('hozmaterms-conditions/', views.terms_conditions, name='terms_conditions'),
    path('products/<int:pno>/', api_views.item_detail_view, name='item_detail'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/products/<int:id>/get-images',api_views.get_product_images,name="product-get-images"),
    #path('delete-all-images/', HozmaApi_views.delete_all_images, name='delete_all_images'),
    #path('api/preorders/', api_views.show_all_preorders, name='show_all_preorders'),
    path('api/confirm-or-update-preorder-items/', HozmaApi_views.confirm_or_update_preorder_items, name='confirm_or_update_preorder_items'),
    #path('api/mainitems/create/', HozmaApi_views.create_mainitem, name='create_mainitem'),
    path('api/mainitems/<int:pk>/update/', HozmaApi_views.update_mainitem, name='update_mainitem'),
    path('api/confirm-or-update-preorder-items-buy-source/', HozmaApi_views.confirm_or_update_preorderBuy_items, name='confirm_or_update_preorderBuy_items'),
    path('api/preorders/', api_views.show_preorders, name='show_all_preorders'),
    path('api/preorders_v2/', api_views.show_preorders_v2, name='show_all_preorders'),
    path('api/preorders-buy/', HozmaApi_views.show_preordersBuy, name='show_all_preorders'),
    path('api/preorders-buy_v2/', HozmaApi_views.show_preorders_buy_v2, name='show_all_preorders'),
    path('preorder-dashboard/', views.dashboard, name='dashboard'),  # For displaying all PreOrders
    path('preorder-detail/<str:invoice_no>/', views.preorder_detail, name='preorder_detail'),  # For displaying a specific PreOrder
    #path('api/test-send-whatsapp/', HozmaApi_views.send_test_whatsapp_message, name='test-send-whatsapp'),
    path('api/full_Sell_invoice_create_item/', HozmaApi_views.full_Sell_invoice_create_item, name='full_Sell_invoice_create_item'),
    path('preorders-buy/', views.preorders_buy_page, name='preorders_buy_page'),
    path('preorders-buy/<str:invoice_no>/', views.preorder_buy_detail, name='preorder-detail'),
    path('send_unsent_invoices/', HozmaApi_views.send_unsent_invoices, name='send_unsent_invoices'),
    path('products/add/<int:clientid>/', views.mainitem_create_page, name='mainitem_create_page'),
    #path('register-source/', views.source_register_view, name='source-register'),
    path('api/show_all_sources/', HozmaApi_views.show_all_sources, name='show_all_sources'),
    path('api/show_source_details/<int:source_id>/', HozmaApi_views.show_source_details, name='show_source_details'),
    path('api/mainitem/create/', HozmaApi_views.create_mainitem_by_source, name='create_mainitem_by_source'),
    path('api/edit_source_info/<int:source_id>/', HozmaApi_views.edit_source_info, name='edit_source_info'),
    path('Handle-source/', views.source_dashboard, name='source_dashboard'),
    path('employees/<int:pk>/get-image/', HozmaApi_views.get_employee_image, name='get-employee-image'),
    path('profile/edit', views.edit_dashboard, name='edit_dashboard'),
    path('api/terms/', HozmaApi_views.create_terms_and_conditions, name='create-terms'),
    path('Admin-Dashboard/', views.Admin_Dashboard, name='Admin_Dashboard'),
    path('Settings/', views.Settings, name='Settings'),
    path('api/producuts/',HozmaApi_views.web_filter_items , name='producuts_detail'),
    #path('api/delete-invoice/', HozmaApi_views.delete_invoice, name='delete-invoice'),
    #path('api/preorder/<int:invoice_no>/delete-items/', HozmaApi_views.delete_preorder_and_items, name='delete-preorder-items-by-invoice-no'),
    #path('api/preorders/delete-all/', HozmaApi_views.delete_all_preorders_and_items, name='delete-all-preorders-and-items'),
    #path('api/preorders_buy/delete-all/', HozmaApi_views.delete_all_preordersBuy_and_items, name='delete-all-preorders-and-items'),
    path('api/preorder/<str:invoice_no>/buy-invoices/', HozmaApi_views.get_buy_invoices_for_preorder),
    path('api/buy-invoice/<int:buy_invoice_no>/preorders/', HozmaApi_views.get_preorders_for_buy_invoice),
    path('api/auto-confirm-preorder/', HozmaApi_views.api_auto_confirm_preorder, name='auto_confirm_preorder'),
    path('api/invoice-summary/', HozmaApi_views.invoice_summary, name='invoice-summary'),
    path('api/invoice-stats/', HozmaApi_views.invoice_statistics),
    path("api/update-client/<int:clientid>/", HozmaApi_views.update_client_info),
    path('api/analytics/items/', HozmaApi_views.item_analytics ,name='item-analytics'),
    path('api/analytics/items/categories/', HozmaApi_views.item_category_analysis, name='item-category-analysis'),
     path('api/analytics/items/prices/', HozmaApi_views.item_price_analysis, name='item-price-analysis'),
    path('api/analytics/items/sources/', HozmaApi_views.item_source_analysis, name='item-source-analysis'),
    path('api/sales-analysis/', HozmaApi_views.SalesAnalysisView, name='sales-analysis'),
    path('api/purchase-analysis/', HozmaApi_views.purchase_analysis, name='purchase-analysis'),
    #path('api/oems/', HozmaApi_views.create_oem_entry, name='create-oem-entry'),
    path('Item_Dashboard/', views.Item_Dashboard, name='Item_Dashboard'),
     path('faq/edit/', views.faq_edit, name='faq_edit'),
    path('api/companies/', HozmaApi_views.get_company_list),
    path('orders/', views.order_view, name='order_view'),
    path('contact/', views.contact, name='contact'),
    path('api/invoice-status-summary/', HozmaApi_views.get_invoice_status_summary),
    path('api/clients/<int:id>/', HozmaApi_views.get_all_clients1, name='get_all_clients1'),
    #path('HOZMAlogin',api_views.Hozma_Login, name='login'),
    path('images/upload/', views.uploadimages, name='upload_images'),
    path('api/return-policy/', HozmaApi_views.return_policy_api_view, name='return_policy_api'),
    path('edit-terms-and-conditions/', views.edit_terms_and_conditions, name='edit_terms_and_conditions'),
    path('return-policy/edit/', views.edit_return_policy, name='edit_return_policy'),
    path('hozmaclient/', views.hozmaclient, name='hozmaclient'),
    path('faq/delete/<int:faq_id>/', views.faq_delete, name='faq_delete'),  
    path('api/item-categories/', HozmaApi_views.get_item_categories_with_counts, name='item-categories-with-counts'),
    path('api/send-whatsapp-contact/', HozmaApi_views.send_whatsapp_message, name='send-whatsapp'),
    #path('api/oemtable/', HozmaApi_views.get_oem_table_data, name='get_oem_table_data'),
    path('api/clients/filter/', HozmaApi_views.filter_clients, name='filter-clients'),
    path('api/client-preorders/', HozmaApi_views.get_client_preorders, name='client-preorders'),
     path('api/preorder/<int:invoice_no>/', HozmaApi_views.get_preorder_with_items_and_client, name='preorder-detail'),
    path('api/item/<str:pno>/details/', HozmaApi_views.item_detail_api, name='item_detail_api'),
    path('api/oemtable/search/', HozmaApi_views.cached_oemtable_list, name='cached-oemtable-list'),
    path('api/company-products/', HozmaApi_views.unique_company_products, name='unique-company-products'),
    path('api/products/<int:id>/get-images',HozmaApi_views.get_product_images,name="product-get-images"),
    path('hozmareport/', views.hozmaReport, name='hozma_report'),
    path('api/invoice-items/<str:invoice_no>/', HozmaApi_views.get_invoice_items, name='get_invoice_items'),
    path('api/employees/drivers/', HozmaApi_views.list_drivers, name='list-drivers'),  # GET
    path('api/preorders/unassigned/', HozmaApi_views.list_unassigned_preorders, name='unassigned-preorders'),  # GET
    path('api/assign-preorder/', HozmaApi_views.assign_preorder, name='assign-preorder'),
    path('api/my-assigned-orders/', HozmaApi_views.my_assigned_orders, name='my-assigned-orders'),
    path('api/download-excel/', HozmaApi_views.create_supplier_packing_list_api, name='download_excel'),
    path('api/dowmload_excel_for_preorder/', HozmaApi_views.download_invoice, name='download_excel_for_preorder'),
    path('api/preorder/create-with-item/', HozmaApi_views.create_preorder_with_item, name='create_pre_order_with_item'),
    path('drivers/',views.Hozmadriver, name='Hozmadriver'),
    path('api/clients/<int:clientId>/details/', HozmaApi_views.client_details, name='client-details'),
    path('api/clients/<int:clientid>/update-pricing/', HozmaApi_views.update_client_price_discount, name='update-client-price-discount'),
    path('delevery-mangment/<int:invoice_no>/', views.HozmaAsgindriver, name='delivery_management'),
    path('api/print', HozmaApi_views.print_api_preorder, name='print_preorder'),
    path('assign-driver/<int:invoice_no>/', HozmaApi_views.available_drivers, name='available-drivers'),
    path('assign-driver/<int:invoice_no>/assign/', HozmaApi_views.assign_driver, name='assign-driver'),
    path('api/delivery/update-items/', HozmaApi_views.update_items, name='update-items'),
    path('api/delivery/confirm-delivery/<int:order_id>/', HozmaApi_views.confirm_delivery, name='confirm-delivery'),
    path('api/delivery/update-status/<int:order_id>/', HozmaApi_views.update_delivery_status, name='update-delivery-status'),
    #path('api/reports/dashboard/', HozmaApi_views.dashboard_report_api, name='dashboard-reports'),
    path('check-preorder-related/<int:buy_invoice_id>/', HozmaApi_views.get_related_preorders, name='check-preorder-related')

    
]




